# YAZI config,
# Maintainer:  Jessee Chan <CYPHER0@foxmail.com>
# Last Change: 2024.10.24


[flavor]
  use = ""

[mgr]
  cwd = { fg = "#a0a050", bold = true }

  # Hovered
  hovered         = { reversed = true, bold = true }
  preview_hovered = { bg = "#202020", bold = true, underline = false }

  # Marker
  marker_marked   = { fg = "#f0e0c0", bg = "#f0e0c0" }
  marker_selected = { fg = "#f0f0c0", bg = "#f0f0c0" }
  marker_copied   = { fg = "#e0c0f0", bg = "#e0c0f0" }
  marker_cut      = { fg = "#f0c0e0", bg = "#f0c0e0" }

  # Count
  count_marked    = { fg = "#f0e0c0", reversed = true, bold = true }
  count_selected  = { fg = "#f0f0c0", reversed = true, bold = true }
  count_copied    = { fg = "#e0c0f0", reversed = true, bold = true }
  count_cut       = { fg = "#f0c0e0", reversed = true, bold = true }

  # Tab
  tab_active      = { fg = "#c0e0f0", reversed = true, bold = true }
  tab_inactive    = {}
  tab_width       = 1

  # Find
  find_keyword    = { fg = "#f0f0c0",               bold = true, italic = true, underline = true }
  find_position   = { fg = "#f0c0f0", bg = "reset", bold = true, italic = true }

  # Border
  border_style    = { fg = "#5080a0" }
  border_symbol   = "|"

  # Highlighting
  syntect_theme   = ""

[mode]
  # mode_normal     = { fg = "#202020", bg = "#c0e0f0", bold = true }
  # mode_select     = { fg = "#101010", bg = "#f0e0c0", bold = true }
  # mode_unset      = { fg = "#101010", bg = "#c0f0f0", bold = true }
  normal_main     = { fg = "#202020", bg = "#c0e0f0", bold = true }
  normal_alt      = { fg = "#c0e0f0", bg = "#202020", bold = true }
  select_main     = { fg = "#101010", bg = "#f0e0c0", bold = true }
  select_alt      = { fg = "#f0e0c0", bg = "#202020", bold = true }
  unset_main      = { fg = "#101010", bg = "#c0f0f0", bold = true }
  unset_alt       = { fg = "#c0f0f0", bg = "#101010", bold = true }

[status]
  # sep_left  = { open = "", close = "" }
  # sep_right = { open = "", close = "" }
  overall   = {}
  sep_left  = { open = "", close = "" }
  sep_right = { open = "", close = "" }

  # Permissions
  perm_sep        = { fg = "#d0d0d0" }
  perm_type       = { fg = "#c0e0f0" }
  perm_read       = { fg = "#5080a0" }
  perm_write      = { fg = "#5080a0" }
  perm_exec       = { fg = "#5080a0" }

  # Progress
  progress_label  = { bold = true }
  progress_normal = { fg = "#c0f0c0", bg = "#001010" }
  progress_error  = { fg = "#f0c0c0", bg = "#001010" }

[select]
  border   = { fg = "#e0f0f0" }
  active   = { fg = "#f0e0f0", bold = true }
  inactive = {}

[input]
  border   = { fg = "#c0e0f0" }
  selected = { reversed = true }
  title    = {}
  value    = {}

[tamts]
  border  = { fg = "#c0c0f0" }
  hovered = { fg = "#f0c0f0", underline = true }
  title   = {}

[which]
  cols            = 2
  mamt            = { bg = "#101010" }
  rest            = { fg = "#d0d0d0" }
  cand            = { fg = "#80a050" }
  desc            = { fg = "#5080a0" }
  separator_style = { fg = "#a0a050", bold = true }
  separator       = " > "

[help]
  on      = { fg = "#c0f0f0" }
  run     = { fg = "#e0f0c0" }
  desc    = {}
  footer  = { fg = "#c0e0f0", bg = "#002030" }
  hovered = { reversed = true, bold = true }

[notify]
  title_info  = { fg = "#c0f0f0" }
  title_warn  = { fg = "#f0f0c0" }
  title_error = { fg = "#f0c0f0" }
  # Icons
  icon_info  = ""
  icon_warn  = ""
  icon_error = ""

[completion]
  border   = { fg = "#e0f0f0" }
  active   = { reversed = true }
  inactive = {}
  # Icons
  icon_folder  = ""
  icon_file    = ""
  icon_command = ""

[filetype]
  rules = [

  # text
    { url = "*.txt",   fg = "#d0d0d0" },
    { url = "*.md",    fg = "#d0d0d0" },
    { url = "*.pdf",   fg = "#d0d0d0" },
    { url = "*.doc",   fg = "#d0d0d0" },
    { url = "*.xls",   fg = "#d0d0d0" },
    { url = "*.ppt",   fg = "#d0d0d0" },
    { url = "*.docx",  fg = "#d0d0d0" },
    { url = "*.xlsx",  fg = "#d0d0d0" },
    { url = "*.pptx",  fg = "#d0d0d0" },

  # image
    { url = "*.jpg",   fg = "#80a050" },
    { url = "*.png",   fg = "#80a050" },
    { url = "*.gif",   fg = "#80a050" },
    { url = "*.bmp",   fg = "#80a050" },
    { url = "*.tif",   fg = "#80a050" },
    { url = "*.tiff",  fg = "#80a050" },

  # audio
    { url = "*.mp3",   fg = "#a05080" },
    { url = "*.m4a",   fg = "#a05080" },
    { url = "*.aac",   fg = "#a05080" },
    { url = "*.ogg",   fg = "#a05080" },
    { url = "*.wav",   fg = "#a05080" },
    { url = "*.flac",  fg = "#a05080" },

  # video
    { url = "*.mp4",   fg = "#8050a0" },
    { url = "*.m4v",   fg = "#8050a0" },
    { url = "*.mkv",   fg = "#8050a0" },
    { url = "*.flv",   fg = "#8050a0" },
    { url = "*.avi",   fg = "#8050a0" },
    { url = "*.webm",  fg = "#8050a0" },

  # archive
    { url = "*.7z",    fg = "#a05050" },
    { url = "*.zip",   fg = "#a05050" },
    { url = "*.rar",   fg = "#a05050" },
    { url = "*.tar",   fg = "#a05050" },
    { url = "*.tgz",   fg = "#a05050" },
    { url = "*.zst",   fg = "#a05050" },
    { url = "*.bz2",   fg = "#a05050" },
    { url = "*.bz3",   fg = "#a05050" },
    { url = "*.bz",    fg = "#a05050" },
    { url = "*.gz",    fg = "#a05050" },
    { url = "*.xz",    fg = "#a05050" },

  # script
    { url = "*.sh",    fg = "#d0d0d0" },
    { url = "*.bsh",   fg = "#d0d0d0" },
    { url = "*.dsh",   fg = "#d0d0d0" },
    { url = "*.py",    fg = "#d0d0d0" },
    { url = "*.pyw",   fg = "#d0d0d0" },

  	{ url = "conf",    fg = "#d0d0d0" },
   	{ url = "cfg",     fg = "#d0d0d0" },
  	{ url = "ini",     fg = "#d0d0d0" },
  	{ url = "cmake",   fg = "#d0d0d0" },

  	{ url = "tmux",    fg = "#d0d0d0" },
  	{ url = "fish",    fg = "#d0d0d0" },
  	{ url = "toml",    fg = "#d0d0d0" },
  	{ url = "yaml",    fg = "#d0d0d0" },
  	{ url = "tmx",     fg = "#d0d0d0" },
  	{ url = "fsh",     fg = "#d0d0d0" },
  	{ url = "tml",     fg = "#d0d0d0" },
  	{ url = "yml",     fg = "#d0d0d0" },
  	{ url = "vimrc",   fg = "#d0d0d0" },
  	{ url = "vim",     fg = "#d0d0d0" },
  	{ url = "lua",     fg = "#d0d0d0" },
  	{ url = "luc",     fg = "#d0d0d0" },

  # Special
    { url = "*",  is = "orphan", bg = "#f0c0c0" },
    { url = "*",  is = "dummy",  bg = "#f0c0c0" },
    { url = "*",  is = "fifo",   fg = "#a08050" },
    { url = "*",  is = "sock",   fg = "#a050a0" },

  # dir
    { url = "*/", is = "dummy",  bg = "#a05050" },
    { url = "*/", is = "link",   fg = "#5050a0", bold = true },
    { url = "*/",                fg = "#50a0a0", bold = true },

  ]

[icon]
  globs = []

  dirs  = [
  	{ name = ".config",   text = "" },
  	{ name = ".git",      text = "" },
  	{ name = "Demttop",   text = "" },
  	{ name = "Downloads", text = "" },
  	# { name = "Public",    text = "" },
  	# { name = "Library",   text = "" },
  	# { name = "Documents", text = "" },
  	# { name = "Pictures",  text = "" },
  	# { name = "Music",     text = "" },
  	# { name = "Movies",    text = "" },
    ]

  exts = [
  	{ name = "txt",    text = "󰈙", fg = "#f0f0f0" },
  	{ name = "md",     text = "", fg = "#e0e0e0" },
  	{ name = "pdf",    text = "", fg = "#f0c0c0" },
  	{ name = "doc",    text = "󰈬", fg = "#c0e0f0" },
  	{ name = "docx",   text = "󰈬", fg = "#c0e0f0" },
  	{ name = "xls",    text = "󰈛", fg = "#c0f0e0" },
  	{ name = "xlsx",   text = "󰈛", fg = "#c0f0e0" },
  	{ name = "ppt",    text = "󰈧", fg = "#f0e0c0" },
  	{ name = "pptx",   text = "󰈧", fg = "#f0e0c0" },

  	{ name = "7z",     text = "", fg = "#f0c0c0" },
  	{ name = "zip",    text = "", fg = "#f0c0c0" },
  	{ name = "rar",    text = "", fg = "#f0c0c0" },
  	{ name = "tar",    text = "", fg = "#f0c0c0" },
  	{ name = "tgz",    text = "", fg = "#f0c0c0" },
  	{ name = "zst",    text = "", fg = "#f0c0c0" },
  	{ name = "bz2",    text = "", fg = "#f0c0c0" },
  	{ name = "bz3",    text = "", fg = "#f0c0c0" },
  	{ name = "bz",     text = "", fg = "#f0c0c0" },
  	{ name = "gz",     text = "", fg = "#f0c0c0" },
  	{ name = "xz",     text = "", fg = "#f0c0c0" },

  # # # #
  	{ name = "jpg",    text = "", fg = "#e0f0c0" },
  	{ name = "png",    text = "", fg = "#e0f0c0" },
  	{ name = "gif",    text = "", fg = "#e0f0c0" },
  	{ name = "bmp",    text = "", fg = "#e0f0c0" },
  	{ name = "tif",    text = "", fg = "#e0f0c0" },
  	{ name = "tiff",   text = "", fg = "#e0f0c0" },

  	{ name = "mp3",    text = "", fg = "#f0c0e0" },
  	{ name = "m4a",    text = "", fg = "#f0c0e0" },
  	{ name = "aac",    text = "", fg = "#f0c0e0" },
  	{ name = "ogg",    text = "", fg = "#f0c0e0" },
  	{ name = "wav",    text = "", fg = "#f0c0e0" },
  	{ name = "flac",   text = "", fg = "#f0c0e0" },

  	{ name = "mp4",    text = "", fg = "#e0c0f0" },
  	{ name = "m4v",    text = "", fg = "#e0c0f0" },
  	{ name = "mkv",    text = "", fg = "#e0c0f0" },
  	{ name = "flv",    text = "", fg = "#e0c0f0" },
  	{ name = "avi",    text = "", fg = "#e0c0f0" },
  	{ name = "webm",   text = "", fg = "#e0c0f0" },

  # # # #
  	{ name = "sh",     text = "", fg = "#f0f0c0" },
  	{ name = "bsh",    text = "", fg = "#f0f0c0" },
  	{ name = "dsh",    text = "", fg = "#f0f0c0" },
  	{ name = "ash",    text = "", fg = "#f0f0c0" },
  	{ name = "py",     text = "", fg = "#f0f0c0" },
  	{ name = "pyw",    text = "", fg = "#f0f0c0" },

  	{ name = "conf",   text = "", fg = "#f0e0c0" },
   	{ name = "cfg",    text = "", fg = "#f0e0c0" },
  	{ name = "ini",    text = "", fg = "#f0e0c0" },
  	{ name = "cmake",  text = "", fg = "#f0e0c0" },

  	{ name = "tmux",   text = "", fg = "#f0e0c0" },
  	{ name = "fish",   text = "", fg = "#f0e0c0" },
  	{ name = "toml",   text = "", fg = "#f0e0c0" },
  	{ name = "yaml",   text = "", fg = "#f0e0c0" },
  	{ name = "tmx",    text = "", fg = "#f0e0c0" },
  	{ name = "fsh",    text = "", fg = "#f0e0c0" },
  	{ name = "tml",    text = "", fg = "#f0e0c0" },
  	{ name = "yml",    text = "", fg = "#f0e0c0" },
  	{ name = "vimrc",  text = "", fg = "#f0e0c0" },
  	{ name = "vim",    text = "", fg = "#f0e0c0" },
  	{ name = "lua",    text = "", fg = "#f0e0c0" },
  	{ name = "luc",    text = "", fg = "#f0e0c0" },

  # # # #
  	{ name = "bin",    text = "", fg = "#e0e0e0" },
  	{ name = "exe",    text = "", fg = "#e0e0e0" },
  	{ name = "apk",    text = "", fg = "#e0e0e0" },
  	{ name = "ko",     text = "", fg = "#e0e0e0" },
  	{ name = "so",     text = "", fg = "#e0e0e0" },
  	{ name = "lib",    text = "", fg = "#e0e0e0" },
  	{ name = "sql",    text = "", fg = "#e0e0e0" },
  	{ name = "obj",    text = "󰆧", fg = "#e0e0e0" },

  	{ name = "rs",     text = "󱘗", fg = "#e0e0e0" },
  	{ name = "rlib",   text = "󱘗", fg = "#e0e0e0" },
  	{ name = "c",      text = "", fg = "#e0e0e0" },
  	{ name = "cpp",    text = "", fg = "#e0e0e0" },
  	{ name = "xml",    text = "󰗀", fg = "#e0e0e0" },
  	{ name = "qml",    text = "", fg = "#e0e0e0" },

  # # # #
  	{ name = "md5",    text = "󰕥", fg = "#e0e0e0" },
  	{ name = "sha1",   text = "󰕥", fg = "#e0e0e0" },
  	{ name = "sha224", text = "󰕥", fg = "#e0e0e0" },
  	{ name = "sha256", text = "󰕥", fg = "#e0e0e0" },
  	{ name = "sha384", text = "󰕥", fg = "#e0e0e0" },
  	{ name = "sha512", text = "󰕥", fg = "#e0e0e0" },

  	{ name = "magnet", text = "", fg = "#e0e0e0" },
  	{ name = "dump",   text = "", fg = "#e0e0e0" },
  	{ name = "img",    text = "", fg = "#e0e0e0" },
  	{ name = "iso",    text = "", fg = "#e0e0e0" },
  	{ name = "ttf",    text = "", fg = "#e0e0e0" },
  	{ name = "m3u",    text = "󰲹", fg = "#e0e0e0" },
  	{ name = "m3u8",   text = "󰲹", fg = "#e0e0e0" },

    ]

  files = [
  	{ name = ".env",   text = "", fg = "reset" },
    ]

  conds = [
    # dir
  	{ if = "dir",    text = "󰉋" },
  	# Special files
  	{ if = "link"  , text = "" },
  	{ if = "fifo"  , text = "" },
  	{ if = "sock"  , text = "" },
  	{ if = "orphan", text = "" },
  	{ if = "dummy",  text = "" },
  	{ if = "block" , text = "" },
  	{ if = "char"  , text = "" },
  	{ if = "sticky", text = "" },
  	{ if = "exec",   text = "" },
  	# Fallback
  	{ if = "!dir",   text = "󰈔" },
    ]


